import { Subject, Deck, Flashcard } from '../types';
import { getTodayDateString, addDaysToDate } from './spacedRepetition';

const today = getTodayDateString();
const yesterday = addDaysToDate(today, -1);
const tomorrow = addDaysToDate(today, 1);
const inThreeDays = addDaysToDate(today, 3);
const inFiveDays = addDaysToDate(today, 5);

export const DEFAULT_SUBJECTS: Subject[] = [
  {
    id: 'subj-med',
    title: 'Medizin & Neuroanatomie',
    description: 'Struktur des Nervensystems, Kranialnerven, Synapsenphysiologie und Hirnareale.',
    colorTheme: 'sage',
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now(),
  },
  {
    id: 'subj-span',
    title: 'Spanisch Sprachpraxis (B2)',
    description: 'Idiomatische Wendungen, Konjunktiv (Subjuntivo) und gehobener Wortschatz.',
    colorTheme: 'amber',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
  },
  {
    id: 'subj-recht',
    title: 'Zivilrecht & BGB',
    description: 'Allgemeiner Teil des BGB, Willenserklärungen, Stellvertretung und Schuldrecht.',
    colorTheme: 'stone',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
];

export const DEFAULT_DECKS: Deck[] = [
  {
    id: 'deck-cranial',
    subjectId: 'subj-med',
    title: 'Kranialnerven & Hirnstamm',
    description: 'Verlauf, Kerngebiete und Innervationsgebiete der 12 Hirnnerven.',
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now(),
  },
  {
    id: 'deck-synapse',
    subjectId: 'subj-med',
    title: 'Synaptische Transmission',
    description: 'Aktionspotenziale, Neurotransmitter, EPSP, IPSP und Rezeptorsubtypen.',
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now(),
  },
  {
    id: 'deck-subjuntivo',
    subjectId: 'subj-span',
    title: 'Subjuntivo & Redewendungen',
    description: 'Wann steht der Subjuntivo presente und pretérito imperfecto?',
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
  },
  {
    id: 'deck-bgb',
    subjectId: 'subj-recht',
    title: 'Willenserklärungen & Anfechtung',
    description: '§§ 119 ff. BGB: Irrtumsarten, Nichtigkeit und wirksame Stellvertretung.',
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
];

export const DEFAULT_CARDS: Flashcard[] = [
  {
    id: 'card-1',
    deckId: 'deck-cranial',
    front: 'Welcher Hirnnerv ist der Nervus vagus und welche Hauptfunktion hat er?',
    back: 'Der X. Hirnnerv (Nervus vagus). Er ist der Hauptnerv des parasympathischen Nervensystems und reguliert Herzfrequenz, Magen-Darm-Trakt und Kehlkopfmuskulatur.',
    hint: 'Lateinisch für "der Umherschweifende"',
    status: 'mastered',
    repetition: 3,
    interval: 6,
    easeFactor: 2.6,
    nextReviewDate: inFiveDays,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
  },
  {
    id: 'card-2',
    deckId: 'deck-cranial',
    front: 'Welcher Hirnnerv vermittelt die mimische Muskulatur des Gesichts?',
    back: 'Der VII. Hirnnerv (Nervus facialis). Er innerviert alle mimischen Muskeln, versorgt Tränen- und Speicheldrüsen und transportiert Geschmacksempfindungen der vorderen 2/3 der Zunge.',
    hint: 'Lähmung führt zur peripheren Fazialisparese.',
    status: 'mastered',
    repetition: 2,
    interval: 3,
    easeFactor: 2.5,
    nextReviewDate: inThreeDays,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
  },
  {
    id: 'card-3',
    deckId: 'deck-cranial',
    front: 'Was sind die drei Hauptäste des Nervus trigeminus (V. Hirnnerv)?',
    back: '1. V1: Nervus ophthalmicus\n2. V2: Nervus maxillaris\n3. V3: Nervus mandibularis (einziger Ast mit motorischen Anteilen für Kaumuskulatur)',
    hint: 'Sensible Versorgung von Stirn, Wange und Unterkiefer.',
    status: 'unsure',
    repetition: 1,
    interval: 1,
    easeFactor: 2.35,
    nextReviewDate: today,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now(),
  },
  {
    id: 'card-4',
    deckId: 'deck-cranial',
    front: 'Welcher Hirnnerv innerviert den Musculus obliquus superior des Auges?',
    back: 'Der IV. Hirnnerv: Nervus trochlearis (Rollnerv). Er ist der einzige Hirnnerv, der dorsal aus dem Hirnstamm austritt.',
    hint: 'Trochlea = Rolle / Umlenkrolle',
    status: 'learning',
    repetition: 0,
    interval: 1,
    easeFactor: 2.1,
    nextReviewDate: today,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now(),
  },
  {
    id: 'card-5',
    deckId: 'deck-cranial',
    front: 'Welche Hirnnerven treten durch das Foramen jugulare aus dem Schädel aus?',
    back: 'N. glossopharyngeus (IX), N. vagus (X) und N. accessorius (XI) zusammen mit der Vena jugularis interna.',
    hint: 'Drei aufeinanderfolgende Nerven (IX, X, XI).',
    status: 'unsure',
    repetition: 1,
    interval: 2,
    easeFactor: 2.3,
    nextReviewDate: tomorrow,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
  {
    id: 'card-6',
    deckId: 'deck-cranial',
    front: 'Welche Funktion hat der XII. Hirnnerv (Nervus hypoglossus)?',
    back: 'Reine motorische Innervation der gesamten Binnen- und Außenmuskulatur der Zunge (mit Ausnahme des M. palatoglossus).',
    hint: 'Unter der Zunge liegend.',
    status: 'new',
    repetition: 0,
    interval: 0,
    easeFactor: 2.5,
    nextReviewDate: today,
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now(),
  },
  {
    id: 'card-7',
    deckId: 'deck-cranial',
    front: 'Aus welchen Anteilen besteht der Nervus vestibulocochlearis (VIII. Hirnnerv)?',
    back: 'Aus dem Nervus vestibularis (Gleichgewichtsorgan) und dem Nervus cochlearis (Hörschnecke). Beide leiten sensorische Afferenzen zum Hirnstamm.',
    status: 'new',
    repetition: 0,
    interval: 0,
    easeFactor: 2.5,
    nextReviewDate: today,
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now(),
  },
  {
    id: 'card-8',
    deckId: 'deck-subjuntivo',
    front: 'Wann verlangt "Ojalá" den Subjuntivo und was drückt es aus?',
    back: '"Ojalá" verlangt IMMER den Subjuntivo! Es drückt einen Wunsch oder ein Hoffen aus. Beispiel: "¡Ojalá tengas suerte!" (Hoffentlich hast du Glück!)',
    hint: 'Gibt es jemals einen Indikativ danach? Nein!',
    status: 'mastered',
    repetition: 3,
    interval: 5,
    easeFactor: 2.6,
    nextReviewDate: inFiveDays,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now(),
  },
  {
    id: 'card-9',
    deckId: 'deck-subjuntivo',
    front: 'Was bedeutet die Redewendung "Costar un ojo de la cara"?',
    back: 'Ein Vermögen / "die Welt" kosten (wörtlich: Ein Auge aus dem Gesicht kosten).',
    status: 'mastered',
    repetition: 2,
    interval: 3,
    easeFactor: 2.5,
    nextReviewDate: inThreeDays,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now(),
  },
  {
    id: 'card-10',
    deckId: 'deck-subjuntivo',
    front: 'Warum heißt es "No creo que venga", aber "Creo que viene"?',
    back: 'Verneinte Verben des Denkens und Glaubens (no creer, no pensar) drücken Zweifel aus und verlangen den Subjuntivo (venga). Bejaht drücken sie Gewissheit aus (viene).',
    status: 'unsure',
    repetition: 1,
    interval: 1,
    easeFactor: 2.3,
    nextReviewDate: today,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
  {
    id: 'card-11',
    deckId: 'deck-bgb',
    front: 'Was ist der Unterschied zwischen Inhaltsirrtum (§ 119 I Alt. 1) und Erklärungsirrtum (§ 119 I Alt. 2 BGB)?',
    back: '- Inhaltsirrtum: Der Erklärende weiß, was er sagt, irrt sich aber über die Bedeutung.\n- Erklärungsirrtum: Die Erklärung weicht vom Willen ab (Versprechen, Vertippen).',
    status: 'mastered',
    repetition: 2,
    interval: 4,
    easeFactor: 2.5,
    nextReviewDate: inThreeDays,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
  {
    id: 'card-12',
    deckId: 'deck-bgb',
    front: 'Welche Rechtsfolge hat eine erfolgreiche Anfechtung nach § 142 Abs. 1 BGB?',
    back: 'Das Rechtsgeschäft ist als von Anfang an (ex tunc) nichtig anzusehen.',
    hint: 'Ex tunc vs. Ex nunc',
    status: 'learning',
    repetition: 0,
    interval: 1,
    easeFactor: 2.2,
    nextReviewDate: today,
    lastReviewed: yesterday,
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
];
